<?php

/**
 * Implements hook_menu().
 */
function fck_modals_menu() {  
  $items['fck_modals'] = array(
    'title' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fck_modals_test_main_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,    
  );
  $items['fck_modals/%ctools_js/login'] = array(
    'title' => '',
    'page callback' => 'fck_modals_login',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,    
  );
  $items['fck_modals/%ctools_js/register'] = array(
    'title' => '',
    'page callback' => 'fck_modals_register',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,    
  );
  $items['fck_modals/%ctools_js/pass'] = array(
    'title' => '',
    'page callback' => 'fck_modals_pass',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,    
  );
  $items['fck_modals/%ctools_js/product/%'] = array(
    'title' => '',
    'page callback' => 'fck_modals_product_detail',
    'page arguments' => array(1,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,    
  );
  
  return $items;
}	

/*
function _md_themesite_modal_content_product_pcb($nid) {
  $node = node_load($nid);
  $content = node_view($node, 'modal_content');
  return print drupal_render($content);
}
 */

/**
 * Implements hook_form_alter().
 */
function fck_modals_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {    
    $form['actions']['submit']['#suffix'] = '<div class="back-to-login clearfix">' . ctools_modal_text_button(t('Back to login'), 'fck_modals/nojs/login', t('Sign in')) . '</div>';
  }
  if ($form_id == 'user_pass') {        
    $form['actions']['#suffix'] = '<div class="back-to-login clearfix">' . ctools_modal_text_button(t('Back to login'), 'fck_modals/nojs/login', t('Sign in')) . '</div>';
  }
  if ($form_id == 'user_login') {
    $form['pass']['#suffix'] = ctools_modal_text_button(t('Forgot your password'), 'fck_modals/nojs/pass', t('Get a new password'));

    if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL) != USER_REGISTER_ADMINISTRATORS_ONLY) {
      $form['actions']['#suffix'] .= "\r<h2>" . t('I don\'t have an account') . "</h2>";
      $form['actions']['#suffix'] .= "\r" . ctools_modal_text_button(t('Create an account'), 'fck_modals/nojs/register', t('Get a new password'));
      $form['actions']['#suffix'] .= '</div>';
    }
  }
}
function fck_modals_test_main_form($form_state) {
  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');

  // Add CTools' javascript to the page.
  ctools_modal_add_js();

  // Create our own javascript that will be used to theme a modal.
  $sample_style = array(
    'ctools-sample-style' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 400,
        'height' => 300,
        'addWidth' => 20,
        'addHeight' => 15,
      ),
      'modalOptions' => array(
        'opacity' => .5,
        'background-color' => '#000',
      ),
      'animation' => 'fadeIn',
      'modalTheme' => 'CToolsSampleModal',
      'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'ctools_ajax_sample'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
    ),
  );

  drupal_add_js($sample_style, 'setting');
  ctools_add_js('ctools-ajax-sample', 'ctools_ajax_sample');
  ctools_add_css('ctools-ajax-sample', 'ctools_ajax_sample');

  $form = array();   
  
  $form['login'] = array(
    '#type' => 'markup',
    '#markup' => ctools_modal_text_button(t('Login'), 'fck_modals/nojs/login', t('Open')),

  );
  $form['register'] = array(
    '#type' => 'markup',
    '#markup' => ctools_modal_text_button(t('Register'), 'fck_modals/nojs/register', t('Open')),
  );
  $form['pass'] = array(
    '#type' => 'markup',
    '#markup' => ctools_modal_text_button(t('Forgot password'), 'fck_modals/nojs/pass', t('Open'), 'ctools-sample-style'),
  );
  $form['product'] = array(
    '#type' => 'markup',
    '#markup' => ctools_modal_text_button(t('Product'), 'fck_modals/nojs/product/167', t('Open'), 'ctools-sample-style'),
  );

  $flag_link = flag_create_link('wishlist', 167);
  $form['wishlist_product'] = array(
    '#markup' => $flag_link,
  );

  $form['flag_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Flag'),
  );
  $form['unflag_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Unflag'),
  );

  return $form;
}

function fck_modals_test_main_form_submit($form, &$form_state) {  
  global $user;
  $product_nid = 167;  
  $flag = flag_get_flag('wishlist');
  $is_flagged = $flag->is_flagged($product_nid, $user->uid);
  if ($form_state['clicked_button']['#parents'][0] == 'flag_submit') {
    dsm('flag');
    if (!$is_flagged) {
      $flag->flag('flag', $product_nid);
    }
  } elseif ($form_state['clicked_button']['#parents'][0] == 'unflag_submit') {
    dsm('unflag');
    if ($is_flagged) {
      $flag->flag('unflag', $product_nid);
    } 
  }
}

/**
 * A modal login callback.
 */
function fck_modals_login($js = NULL) {
  // Fall back if $js is not set.
  if (!$js) {
    return drupal_get_form('user_login');
  }

  ctools_include('modal');
  ctools_include('ajax');
  $form_state = array(
    'title' => t('Login'),
    'ajax' => TRUE,
  );
  $output = ctools_modal_form_wrapper('user_login', $form_state);
  if (!empty($form_state['executed'])) {
    // We'll just overwrite the form output if it was successful.
    $output = array();
    $output[] = ctools_ajax_command_reload();
    $output[] = ctools_modal_command_dismiss();
  }
  print ajax_render($output);
  exit;
}

/**
 * A modal Register callback.
 */
function fck_modals_register($js = NULL) {
  // Fall back if $js is not set.
  if (!$js) {
    return drupal_get_form('user_register_form');
  }

  ctools_include('modal');
  ctools_include('ajax');
  $form_state = array(
    'title' => t('Register'),
    'ajax' => TRUE,
  );
  $output = ctools_modal_form_wrapper('user_register_form', $form_state);
  if (!empty($form_state['executed'])) {
    // We'll just overwrite the form output if it was successful.
    $output = array();    
    $email = $form_state['values']['mail'];
    $message = t('Registration is successful. Mail with confimation has been sent to !email', array('!email' => $email));
    $output[] = ctools_modal_command_display(t('Sign up success'), $message);
    //$output[] = ctools_modal_command_dismiss();
  }
  print ajax_render($output);
  exit;
}

/**
 * A modal Forgot password callback.
 */
function fck_modals_pass($js = NULL) {
  // Fall back if $js is not set.
  if (!$js) {
    return drupal_get_form('user_pass');
  }

  ctools_include('modal');
  ctools_include('ajax');
  ctools_include('user.pages', 'user', ''); 
  $form_state = array(
    'title' => t('Forgot password'),
    'ajax' => TRUE,
  );
  $output = ctools_modal_form_wrapper('user_pass', $form_state);
  if (!empty($form_state['executed'])) {
    // We'll just overwrite the form output if it was successful.    
    $output = array();    
    $email = $form_state['values']['name'];
    $message = t('Mail with reset instructions has been sent to !email', array('!email' => $email));
    $output[] = ctools_modal_command_display(t('Forgot password'), $message);    
  }
  print ajax_render($output);
  exit;
}

function fck_modals_product_detail($js = NULL, $product_nid = NULL) {
  if (is_null($product_nid)) {
    return '';
  }
  $node = node_load($product_nid);

  $content = node_view($node, 'modal_product_detail');
  $content = drupal_render($content);

  ctools_include('modal');
  ctools_include('ajax');

  // Fall back if $js is not set.
  if (!$js) {
    return $content;
  }

  $output[] = ajax_command_invoke('.modal-dialog', 'addClass', array('fck-product-detail'));
  $output[] = ctools_modal_command_display(t('Forgot password Success'), $content);
  print ajax_render($output);
  exit;
}