<?php

/**
 * Implement hook_node_presave()
 */
function commerce_stock_filter_node_presave($node) {
	if ($node->type == 'shop_product') {
		// ignore this hook if product display updates 
		// from Commerce Stock Filter rules actions
		if (isset($node->csf_ignore)) {
			unset($node->csf_ignore);
			return;
		}

		$wrapper = entity_metadata_wrapper('node', $node);
		// calculate a stock of all product variantions
		$total_stock = 0;
		foreach ($wrapper->field_product_store as $product) {
			$total_stock += $product->commerce_stock->value();
		}		
		// if total stock > 0 and product display is unpublished -
		// publish a product display		
		if ($total_stock && !$node->status) {
			$node->status = TRUE;
		} 
		// if total stock = 0 and product display is published -
		// unpublish a product display
		elseif (!$total_stock && $node->status) {
			$node->status = FALSE;
		}
	}	
}