<?php

/**
 * Implements hook_menu().
 */
function fck_admin_menu() {  
  $items['admin/fck'] = array(
    'title' => 'FCK',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fck_admin_settings_form'),
    'access arguments' => array('administer fck admin'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'fck_admin.settings.inc',
  );
  
  $items['admin/fck/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fck_admin_settings_form'),
    'access arguments' => array('administer fck admin'),
    'type' => MENU_DEFAULT_LOCAL_TASK,  
    'file' => 'fck_admin.settings.inc',
    'weight' => 0,
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function fck_admin_permission() {
  return array(    
    'administer fck admin' =>  array(
      'title' => t('Administer FCK Admin'),
      'description ' => t('Perform administration tasks for FCK Admin'),
    ),
  );
}

/**
 * Implements hook_admin_paths().
 */
function fck_admin_admin_paths() {
  $paths = array(
    'admin/fck/*' => TRUE,
  );
  
  return $paths;   
}	

/**
 * Implements hook_form_alter().
 */
function fck_admin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'shop_product_node_form') {
    //dsm($form);
    $form['field_weight_hot']['#access'] = FALSE;
    $form['field_weight_new']['#access'] = FALSE;
    $form['field_weight_featured']['#access'] = FALSE;
    $form['field_weight_clothing']['#access'] = FALSE;
    $form['field_weight_jersey']['#access'] = FALSE;
    $form['field_weight_accessories']['#access'] = FALSE;
    $form['field_weight_match_kits']['#access'] = FALSE;
    $form['field_weight_gifts']['#access'] = FALSE;
    $form['field_weight_baby']['#access'] = FALSE;
    $form['field_weight_sale']['#access'] = FALSE;
  }
}
